### PR TITLE
Session should generate on login

### PR DESCRIPTION
**Pull request by nick-potts**

### CODE REVIEW

**Comment by nick-potts** [comment]
fixes #1

**Comment by stevebauman** [comment]
Hi @nick-potts, why is this necessary? Isn't this already done via `Auth::login()`?

https://github.com/laravel/framework/blob/b9e4c7a27f30f05a87563f82b4917c544f8eb1bd/src/Illuminate/Auth/SessionGuard.php#L516-L525

https://github.com/laravel/framework/blob/b9e4c7a27f30f05a87563f82b4917c544f8eb1bd/src/Illuminate/Auth/SessionGuard.php#L544-L555

https://github.com/laravel/framework/blob/b9e4c7a27f30f05a87563f82b4917c544f8eb1bd/src/Illuminate/Session/Store.php#L596-L613

I've never had to do this in any Laravel app previously

**Comment by stevebauman** [comment]
Confirmed that this isn't needed as Laravel already handles this under the hood.

**Comment by nick-potts** [comment]
Laravel does the session automatically, but not the CSRF token - which is covered by this.

Not a huge issue, but laravel does recommend it in the docs:
https://laravel.com/docs/11.x/authentication#authenticating-users

**Comment by stevebauman** [comment]
Thanks for the link @nick-potts! News to me, had no idea, appreciate the PR 🙏

**Pull request merged**
